API_URL = ""
SUPABASE_URL      = "https://cvjmrqlhdnjuxbkczwrn.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2am1ycWxoZG5qdXhia2N6d3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTExNzYyMzUsImV4cCI6MjEwNjc1MjIzNX0.-uaf6X6A2LfKQ0yqv-zI02KDmfVnpG9WuH54q-CYeho"

